# NumPy
## Practice Problems

### 1. The formula for exponential growth is `population_size = N0 *e**rt`, where `N0` is the initial population, `e` is the exponential function, `r` is the rate, and `t` is time. Using this:

1.   Set the initial population, `N0`, as 100 and the growth rate, `r`, as 0.4
2.   Use the suitable `numpy` function to generate an array of time points, `t`, which go from 0 to 10 seconds, in 0.2 second increments.
3.   Write an expression to evaluate `population_size`, which should be an array of the population size for each time point in `t`.
4.   Create a new variable called `population_size_noise`, use the same expression you wrote in parts (3), and add noise to the population at each time point. Do this by adding an expression that uses a `numpy` function to generate a random value for each time point drawn from a normal distribution of `mean=0` and `stdev=250` (i.e., population_size_noise = expression_from_part_a + expression_to_add_noise).

In [4]:
# Your code here
import numpy as np
N0 =100
growth_rate = 0.4
t = np.arange(0, 10.2, 0.2) # stop is set to 10.2 as increments are 0.2 
population_size = N0 * np.exp(growth_rate * t)
print("Population size  ", population_size)
population_size_noise =   N0 * np.exp(growth_rate * t) + np.random.normal(0,250, np.shape(population_size))
print("Noise :", population_size_noise)


Population size   [ 100.          108.32870677  117.3510871   127.12491503  137.71277643
  149.18246976  161.60744022  175.06725003  189.64808793  205.44332106
  222.55409285  241.08997064  261.16964734  282.92170144  306.48542033
  332.01169227  359.66397256  389.61933018  422.0695817   457.22251951
  495.30324244  536.55559711  581.24373944  629.6538261   682.09584693
  738.90560989  800.44689143  867.11376585  939.33312874 1017.56743061
 1102.31763806 1194.12644178 1293.58173155 1401.32036077 1518.0322245
 1644.46467711 1781.42731796 1929.79717555 2090.52432351 2264.63796432
 2453.25301971 2657.57726999 2878.91908792 3118.69581683 3378.44284638
 3659.82344437 3964.63940726 4294.84259788 4652.54744398 5040.04447781
 5459.81500331]
Noise : [ 106.00265828  692.63462408  -42.75668684  263.4026899   255.75274535
  115.14558525   78.73387233 -140.56612026  106.3687504    59.33439047
  408.50790192  347.73048223  563.69410424  256.13418743   25.1435455
  461.8425568   283.38881312  416.249

<details>
  <summary>Answer</summary>

  ```python
  import numpy as np

  #set initial population
  N0 = 100
  #set growth rate
  rate = 0.4
  #create array of time points 
  t = np.arange(start=0, stop=10.2, step=0.2)

  #calculate population of colony at the time points in t
  population_size = N0 * np.exp(rate*t)
  print('Population size is: ',population_size)

  #add noise to population at each time point
  population_size_noise = N0 * np.exp(rate*t) + np.random.normal(loc=0, scale=250, size=np.shape(population_size))
  print('Population size with noise is: ',population_size_noise)
  ```
</details>

### 2. Create a multiplication table for the number 6.

In [11]:
# Your code here
import numpy as np

def multiplication_table(n):
    arr = np.arange(1,n+1)
    return np.multiply( arr , arr[:,None])

print("Multiplication table for 4 \n", multiplication_table(4))
print("Multiplication table for 5 \n",multiplication_table(5))
print("Multiplication table for 6 \n",multiplication_table(6))

Multiplication table for 4 
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
Multiplication table for 5 
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
Multiplication table for 6 
 [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


<details>
  <summary>Answer</summary>

  ```python
  rows = np.arange(1, 7)
  columns = rows[:,np.newaxis]
  arr = rows * columns
  arr
  ```
</details>

### 3. Slice `arr` to create the following two arrays:

`arr1` = [4, 12, 3]

`arr2` = [3, 19]

In [ ]:
# Your code here

<details>
  <summary>Answer</summary>

  ```python
  arr = np.array([[4, 12, 98], [12, 11, 92], [3, 19, 60]])
  arr

  arr1 = arr[:,0]
  print(arr1)

  arr2 = arr[2,0:2]
  print(arr2)
  ```
</details>